<ScatterTextWidget>:
    orientation: 'vertical'
    TextInput:
        id: my_text_input
        font_size: 20
        size_hint_y: None
        height: 200
        text: 'default'
        on_text: root.change_label_colour()

    FloatLayout:
        Scatter:
            Label:
                id: my_label
                text: my_text_input.text
                font_size: 20
                color: root.text_colour
